### ISSUE TITLE
android detection

### ISSUE THREAD

**Issue by kaspar-allenbach** [mmikkel/Detect-Craft#1]
Hi.

This works:

```
{% if isUserMobile %}
  {# blabla #}
{% endif %}
```

but this doesn't:

```
{% if isAndroidOS %}
  {# blabla #}
{% endif %}
```

This returns: 

> Variable "isAndroidOS" does not exist

Why?

**Comment by mmikkel** [comment]
That error is unrelated to Detect; it simply means that you haven't actually set the `isAndroidOS` variable you're testing.

You'll either need to do this:

``` jinja
{% if craft.detect.isAndroidOS %}
    {# blabla #}
{% endif %}
```

...or this:

``` jinja
{% set isAndroidOS = craft.detect.isAndroidOS %}
{% if isAndroidOS %}
    {# blabla #}
{% endif %}
```
